"""A deterministic first pass over a pull request.

This is *not* an AI code review: it is the checklist a careful teammate runs
through in the first minute - description, linked issue, size, tests, CI.

    $ 2pro automate review owner/repo 42 --post
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from ..github import GitHub

__all__ = ["Finding", "Level", "ReviewReport", "review_pr"]

LINKED_ISSUE = re.compile(r"(?i)\b(close[sd]?|fix(e[sd])?|resolve[sd]?)\s+#(\d+)")
TEST_PATTERNS = re.compile(
    r"(^|/)(tests?|spec)/|_test\.|test_[^/]*\.py|\.test\.[jt]sx?$|\.spec\.[jt]sx?$",
    re.IGNORECASE,
)
SOURCE_PATTERNS = re.compile(r"\.(py|js|ts|tsx|jsx|go|rs|java|rb|php|cs|c|cpp|h)$", re.IGNORECASE)
SECRET_PATTERNS = re.compile(
    r"(api[_-]?key|secret|password|passwd|token)\s*[:=]\s*['\"][^'\"\s]{8,}", re.IGNORECASE
)


class Level(str, Enum):
    """Severity of a review finding."""

    ERROR = "error"
    WARNING = "warning"
    INFO = "info"
    PRAISE = "praise"

    @property
    def icon(self) -> str:
        return {
            "error": "🚫",
            "warning": "⚠️",
            "info": "ℹ️",  # noqa: RUF001 - the icon is intentional
            "praise": "👏",
        }[self.value]


@dataclass
class Finding:
    """One observation about a pull request."""

    level: Level
    message: str
    rule: str = ""

    def __str__(self) -> str:  # pragma: no cover - cosmetic
        return f"{self.level.icon} {self.message}"


@dataclass
class ReviewReport:
    """The full review: findings, verdict and the rendered comment."""

    repo: str
    number: int
    title: str
    findings: list[Finding] = field(default_factory=list)
    files: list[dict[str, Any]] = field(default_factory=list)
    dry_run: bool = True
    posted: bool = False

    @property
    def errors(self) -> list[Finding]:
        return [f for f in self.findings if f.level is Level.ERROR]

    @property
    def warnings(self) -> list[Finding]:
        return [f for f in self.findings if f.level is Level.WARNING]

    @property
    def verdict(self) -> str:
        if self.errors:
            return "changes requested"
        if self.warnings:
            return "looks good with comments"
        return "looks good to me"

    @property
    def markdown(self) -> str:
        lines = [
            "## 🤖 2pro automated review",
            "",
            f"**Verdict: {self.verdict}** "
            f"({len(self.errors)} blocker(s), {len(self.warnings)} warning(s))",
            "",
        ]
        if not self.findings:
            lines.append("No issues found - nice work.")
            lines.append("")
        else:
            lines.append("| | Finding | Rule |")
            lines.append("| --- | --- | --- |")
            for finding in self.findings:
                lines.append(
                    f"| {finding.level.icon} | {_escape(finding.message)} | `{finding.rule}` |"
                )
            lines.append("")

        additions = sum(f.get("additions", 0) for f in self.files)
        deletions = sum(f.get("deletions", 0) for f in self.files)
        lines.append(
            f"<sub>{len(self.files)} file(s) changed, +{additions}/-{deletions} · "
            f"generated by <b>2pro</b></sub>"
        )
        return "\n".join(lines)


def analyze(
    title: str,
    body: str | None,
    files: list[dict[str, Any]],
    *,
    draft: bool = False,
    additions: int = 0,
    deletions: int = 0,
    ci_conclusion: str | None = None,
    requested_reviewers: int = 0,
    has_description_template: bool = False,
) -> list[Finding]:
    """Pure function: turn PR metadata into findings (easy to unit test)."""
    findings: list[Finding] = []
    text = (body or "").strip()

    if draft:
        findings.append(Finding(Level.INFO, "This pull request is still a draft.", "draft"))
    if len(text) < 30:
        findings.append(
            Finding(
                Level.WARNING,
                f"The description is very short ({len(text)} characters) - "
                "explain what changed and why.",
                "description-length",
            )
        )
    if not LINKED_ISSUE.search(text):
        findings.append(
            Finding(
                Level.INFO,
                "No linked issue found - add `Closes #123` so the issue closes automatically.",
                "linked-issue",
            )
        )
    if additions + deletions > 600:
        findings.append(
            Finding(
                Level.WARNING,
                f"This is a large change ({additions + deletions} lines) - "
                "consider splitting it into smaller pull requests.",
                "pr-size",
            )
        )
    elif additions + deletions <= 20:
        findings.append(Finding(Level.PRAISE, "Small, focused change - easy to review.", "pr-size"))

    paths = [str(f.get("filename", "")) for f in files]
    source_changed = [p for p in paths if SOURCE_PATTERNS.search(p)]
    tests_changed = [p for p in paths if TEST_PATTERNS.search(p)]
    if source_changed and not tests_changed:
        findings.append(
            Finding(
                Level.WARNING,
                f"{len(source_changed)} source file(s) changed but no tests were touched.",
                "missing-tests",
            )
        )
    if tests_changed and not source_changed:
        findings.append(Finding(Level.PRAISE, "Test-only change.", "tests-only"))

    for file_info in files:
        patch = file_info.get("patch") or ""
        if SECRET_PATTERNS.search(patch):
            findings.append(
                Finding(
                    Level.ERROR,
                    f"Possible hardcoded secret in `{file_info.get('filename')}`.",
                    "no-secrets",
                )
            )
            break

    if ci_conclusion == "failure":
        findings.append(Finding(Level.ERROR, "CI is failing on this pull request.", "ci"))
    elif ci_conclusion == "success":
        findings.append(Finding(Level.PRAISE, "All checks are green.", "ci"))
    if not requested_reviewers:
        findings.append(Finding(Level.INFO, "No reviewers requested yet.", "reviewers"))
    if has_description_template and not text:
        findings.append(
            Finding(Level.WARNING, "The pull request template was not filled in.", "template")
        )
    if title and not re.match(r"^[a-z]+(\([^)]*\))?!?:\s", title):
        findings.append(
            Finding(
                Level.INFO,
                "Title is not in Conventional Commits form (e.g. `feat(api): add paging`).",
                "conventional-title",
            )
        )

    return findings


def review_pr(
    gh: GitHub,
    repo: str,
    number: int,
    *,
    post: bool = False,
    dry_run: bool = True,
    update_existing: bool = True,
) -> ReviewReport:
    """Analyze a pull request and optionally post the result as a comment."""
    from ..client import guess_repo_path

    owner, name = guess_repo_path(repo)
    pr = gh.pulls.get(owner, name, number)
    files = list(gh.pulls.files(owner, name, number, max_items=300))

    ci_conclusion: str | None = None
    if pr.head:
        for run in gh.actions.runs(owner, name, head_sha=pr.head.sha, max_items=20):
            if run.is_completed and run.is_failure:
                ci_conclusion = "failure"
                break
            if run.is_completed and run.is_success:
                ci_conclusion = run.conclusion

    findings = analyze(
        pr.title,
        pr.body,
        files,
        draft=bool(pr.draft),
        additions=pr.additions,
        deletions=pr.deletions,
        ci_conclusion=ci_conclusion,
        requested_reviewers=len(pr.requested_reviewers),
    )
    report = ReviewReport(
        repo=f"{owner}/{name}",
        number=number,
        title=pr.title,
        findings=findings,
        files=files,
        dry_run=dry_run,
    )

    should_write = post and not dry_run
    if should_write:
        body = report.markdown
        existing = _find_bot_comment(gh, owner, name, number) if update_existing else None
        if existing:
            gh.issues.update_comment(owner, name, existing.id or 0, body)
        else:
            gh.issues.comment(owner, name, number, body)
        report.posted = True
    return report


def _find_bot_comment(gh: GitHub, owner: str, name: str, number: int) -> Any | None:
    for comment in gh.issues.comments(owner, name, number, max_items=100):
        if comment.body and "2pro automated review" in comment.body:
            return comment
    return None


def _escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")
